<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'johnny/delete-me',
        'dev' => true,
    ),
    'versions' => array(
        'codeguy/upload' => array(
            'pretty_version' => '1.3.2',
            'version' => '1.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeguy/upload',
            'aliases' => array(),
            'reference' => '6a9e5e1fb58d65346d0e557db2d46fb25efd3e37',
            'dev_requirement' => false,
        ),
        'grocerycrud/enterprise' => array(
            'pretty_version' => '2.9.4',
            'version' => '2.9.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grocerycrud/enterprise',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'johnny/delete-me' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'laminas/laminas-db' => array(
            'pretty_version' => '2.14.1',
            'version' => '2.14.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-db',
            'aliases' => array(),
            'reference' => '7daba1149e69dc828ce083844cde1101c0418afa',
            'dev_requirement' => false,
        ),
        'laminas/laminas-stdlib' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-stdlib',
            'aliases' => array(),
            'reference' => 'bcd869e2fe88d567800057c1434f2380354fe325',
            'dev_requirement' => false,
        ),
        'scoumbourdis/phpexcel' => array(
            'pretty_version' => '1.9.4',
            'version' => '1.9.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scoumbourdis/phpexcel',
            'aliases' => array(),
            'reference' => '837abe26d0056c3f1254f2045d753fcd2b35d47c',
            'dev_requirement' => false,
        ),
        'vlucas/valitron' => array(
            'pretty_version' => 'v1.4.10',
            'version' => '1.4.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/valitron',
            'aliases' => array(),
            'reference' => '5ebd5d7af82cc0a9d798e816a2ecad63f1b59ceb',
            'dev_requirement' => false,
        ),
    ),
);
